import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { contractShapes, replShapes } from "./__fixtures__/harness";

/**
 * JSON contract: every external JSON shape (Command, PlayerState, Observation, MapView, Result, every GameEvent type,
 * the devil request, the REPL --json lines) may only grow. Each path recorded before the stateless refactor must still
 * exist with exactly the same JSON types; new paths are allowed.
 */
const load = (f: string) => JSON.parse(readFileSync(new URL(`./__fixtures__/${f}`, import.meta.url), "utf8")) as Record<string, string[]>;
/** Frozen: recorded with the pre-refactor class engine. */
const baseline = load("contract.json");
/** The contract as of the stateless engine, new fields and events included (regenerated by generate.ts). */
const current = load("contract-current.json");

/**
 * Fields the Deal type has always declared optional (`curse?`, `rewrite?`). The baseline sampler happened to see them
 * present every time; a sample where they are absent is not a contract change. Only these, and only "absent" added.
 */
const DECLARED_OPTIONAL = /\.offer\.(curse|rewrite)$/;
const same = (path: string, was: string[], now: string[] | undefined): boolean => {
  if (JSON.stringify(now) === JSON.stringify(was)) return true;
  if (!now || !DECLARED_OPTIONAL.test(path)) return false;
  return JSON.stringify(now.filter((t) => t !== "absent")) === JSON.stringify(was.filter((t) => t !== "absent"));
};
const breaks = (recorded: Record<string, string[]>, now: Record<string, string[]>, only = "") => Object.entries(recorded)
  .filter(([path]) => path.startsWith(only))
  .filter(([path, types]) => !same(path, types, now[path]))
  .map(([path, types]) => `${path}: was ${types.join("|")}, now ${now[path]?.join("|") ?? "missing"}`);

test("JSON contract: changes are additive only (no field removed, renamed or retyped)", async () => {
  assert.deepEqual(breaks(baseline, await contractShapes()), [], "vs the pre-refactor baseline");
  assert.deepEqual(breaks(current, await contractShapes({ includeNew: true })), [], "vs contract-current.json (incl. actions, awaiting, game_state, curses, asksLeft, devil_stage_*)");
});

test("JSON contract: REPL --state only adds game_state (a full, JSON-safe GameState) to the same lines", () => {
  const now = replShapes(["--state"]);
  assert.deepEqual(breaks(baseline, now, "repl:"), []);
  for (const k of ["repl:report.game_state.seed", "repl:report.game_state.rng.s", "repl:report.game_state.acts[]", "repl:report.actions[]", "repl:map.game_state.seed"]) assert.ok(now[k], k);
});
