/**
 * Bundle server/devil-core.ts (and what it imports from src/) into api/_lib/devil.mjs, one self-contained ESM file for the
 * Vercel function api/deal.ts, with devil_prompt.txt inlined. Vercel compiles api/*.ts file by file, and Node's ESM
 * loader can't follow the extensionless and directory imports in src/, so the function imports this bundle instead.
 * `npm run build:api` writes it (commit the result); `bundleApi()` returns it, so a test can check the committed copy is
 * fresh. Uses esbuild (installed with tsx). docs/deploy-vercel.md.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("..", import.meta.url));
export const API_BUNDLE = fileURLToPath(new URL("../api/_lib/devil.mjs", import.meta.url));

export async function bundleApi(): Promise<string> {
  const rules = readFileSync(new URL("../devil_prompt.txt", import.meta.url), "utf8").trim();
  const r = await build({
    absWorkingDir: root, entryPoints: ["server/devil-core.ts"], bundle: true, write: false,
    platform: "node", format: "esm", target: "node20", legalComments: "none", logLevel: "warning",
    define: { __DEVIL_RULES__: JSON.stringify(rules) },
    banner: { js: "// GENERATED by `npm run build:api` from server/devil-core.ts and devil_prompt.txt. Do not edit; rebuild and commit." },
  });
  return r.outputFiles[0].text;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const js = await bundleApi();
  writeFileSync(API_BUNDLE, js);
  console.log(`wrote ${API_BUNDLE} (${(js.length / 1024).toFixed(1)} KB)`);
}
